-- CREATE MSSQL Database and its table structure

USE [master]
GO


CREATE DATABASE [Arbitron]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Arbitron', FILENAME = N'D:\DATA\MSSQL14.MSSQLSERVER\MSSQL\DATA\Arbitron.mdf' , SIZE = 512MB , MAXSIZE = UNLIMITED, FILEGROWTH = 100MB )
 LOG ON 
( NAME = N'Arbitron_log', FILENAME = N'D:\DATA\MSSQL14.MSSQLSERVER\MSSQL\DATA\Arbitron_log.ldf' , SIZE = 512MB , MAXSIZE = 2048MB , FILEGROWTH = 100MB )
GO

ALTER DATABASE [Arbitron] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Arbitron].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Arbitron] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Arbitron] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Arbitron] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Arbitron] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Arbitron] SET ARITHABORT OFF 
GO

ALTER DATABASE [Arbitron] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Arbitron] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Arbitron] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Arbitron] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Arbitron] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Arbitron] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Arbitron] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Arbitron] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Arbitron] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Arbitron] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Arbitron] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Arbitron] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Arbitron] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Arbitron] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Arbitron] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Arbitron] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Arbitron] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Arbitron] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Arbitron] SET  MULTI_USER 
GO

ALTER DATABASE [Arbitron] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Arbitron] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Arbitron] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Arbitron] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Arbitron] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Arbitron] SET QUERY_STORE = OFF
GO

USE [Arbitron]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Arbitron] SET  READ_WRITE 
GO



USE Arbitron
go

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[history](
	[insert_date] [datetime] NULL,
	[timestamp] [numeric](38, 0) NULL,
	[ts] [datetime] NOT NULL,
	[exchange] [varchar](12) NOT NULL,
	[pair] [varchar](10) NOT NULL,
	[price] [decimal](38, 12) NOT NULL,
	[amount] [decimal](38, 12) NOT NULL,
	[type] [varchar](12) NULL,
	[side] [varchar](12) NULL,
	[id] [varchar](50) NULL
) ON [PRIMARY]
GO


ALTER TABLE [dbo].[history] REBUILD PARTITION = ALL WITH (DATA_COMPRESSION = PAGE)
GO

/*
CREATE NONCLUSTERED COLUMNSTORE INDEX [NCCI_history] ON [dbo].[history]
(
	[exchange],
	[pair]
)WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY]
GO


ALTER INDEX [NCCI_history] ON [dbo].[history] REBUILD PARTITION = ALL WITH (DATA_COMPRESSION = COLUMNSTORE_ARCHIVE)
GO
*/

CREATE CLUSTERED COLUMNSTORE INDEX [CCI_history] ON [dbo].[history] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY]